### ISSUE TITLE
[improvement] krok platba

### ISSUE THREAD

**Issue by serusko** [slovensko-digital/priznanie-digital#443]
v prvom rade palec hore, spravil som si priznanie za 5minut 
akurat posledny krok "platba" bol chaoticky az natolko ze mi vypadol VS a musim to este doriesit aby mi to sparovali 

mozno namiesto odkazu na oficialny navod ako zaplatit 
by bolo dobre vyzdvihnut existujuci generator na financnej sprave "Vytvorenie platobných inštrukcií" 
ktory som nevidel ani v oficialnom navode a nasiel som ho az teraz

je dostupny po prihlaseni na fin spravu

Home -> Osobná internetová zóna -> Osobný účet -> Vytvorenie platobných inštrukcií

https://www.financnasprava.sk/sk/osobna-internetova-zona/osobny-ucet/vytvorenie-platobnych-instrukc

**Comment by jsuchal** [comment]
@serusko toto sa "podarilo fixnut" uplne inac a poriadne. FS pochopila a spravili platbu cez kartu rovno u nich ked podas DP. Cize zatvaram :)
