### ISSUE TITLE
Odkaz v emaili cez env vars

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/priznanie-digital#721]
Momentalne musime synchronizovat sablony na sendinblue na prod/stage lebo odkazy na navodoch sa zvyknu mierne lisit medzi prostrediami aj rokmi. Po tom co @MarekVigas uz dal do env odkazy ktore idu na centralu kvoli tomu, aby vedela kam redirectnut po flowe ale treba toto dostat aj do emailu. Sablonu na sendinblue upravit vieme lahko, v kode vsak treba tento parameter posielat.

Netreba riesit teraz - tento release dobojujeme bez toho.

**Comment by MarekVigas** [comment]
pozri #720

**Comment by jsuchal** [comment]
@MarekVigas ano viem, ale asi som to prilis z rychlika napisa. My mame ste aj sendinblue (to co posiela emaily) v dvoch prostrediach a su tam 2 typy sablon staging/prod lebo sa lisia len v linke na dalsi krok. Kedze uz tieto kroky nemame hardcoded (vid tvoj PR) tak este keby sme ich cez parameter dostali do sablony emailu, tak uz nemusime nic menit medzi stage/prod v sendinblue.

![image](https://user-images.githubusercontent.com/26342/224303000-c4ca8226-f9b4-4ade-81af-735958006096.png)

**Comment by jsuchal** [comment]
Doslova by malo stacit toto (ale plna url nie len path) https://github.com/slovensko-digital/priznanie-digital/blob/4d02e4134cebe7f143499b5fbb189d3a0f620c56/src/pages/odklad/pokracovat.tsx#L26

dat **aj** sem  nejako https://github.com/slovensko-digital/priznanie-digital/blob/4d02e4134cebe7f143499b5fbb189d3a0f620c56/src/pages/odklad/pokracovat.tsx#L58-L65

A pre danove to iste.
