### ISSUE TITLE
Uplatnenie 2% ked nemam narok

### ISSUE THREAD

**Issue by MarekVigas** [slovensko-digital/priznanie-digital#740]
> v príklade č. 4 mi vyskočila možnosť darovať 2 %, pričom možnosť darovania nie je, keďže daň, z ktorej sa počítajú 2 % bola vo výške 0 EUR

https://github.com/slovensko-digital/priznanie-digital/blob/master/__tests__/testCases/case202204Input.ts
https://github.com/slovensko-digital/priznanie-digital/blob/master/__tests__/examples/2022/SK%20Digital_110223_DP%20FO%20typ%20B_Priklad%20c.%204.pdf
https://github.com/slovensko-digital/priznanie-digital/blob/master/__tests__/examples/2022/SK%20Digital_110223_DP%20FO%20typ%20B_Priklad%20c.%204.xml

**Comment by MarekVigas** [comment]
@JakubMurin toto je vyriešené však ?

**Comment by JakubMurin** [comment]
Hej, keďže sa to vždy zobrazuje.
Ale vypíše, že sa nedá darovať.
