### ISSUE TITLE
Pouzit conditional field pri zaciatku prijmov

### ISSUE THREAD

**Issue by MarekVigas** [slovensko-digital/priznanie-digital#746]
![image](https://user-images.githubusercontent.com/11539820/227456257-65128d5c-c988-403f-8714-ff99c17ed238.png)

**Comment by MarekVigas** [comment]
https://slovensko-digital.slack.com/archives/CU5QZ04G7/p1678435409886599

**Comment by ioannes-vetus** [comment]
V ramci quick-fix som upravil css styles podla gov uk repozitara (https://github.com/alphagov/govuk_elements/blob/master/assets/sass/elements/_panels.scss). Do buducna bude lepsie preskumat moznosti vyuzitia kniznice https://www.npmjs.com/package/navody-digital-frontend (ktora je, zda sa, outdated).
