### ISSUE TITLE
odstranit floorDecimal / ceilDecimal

### ISSUE THREAD

**Issue by MarekVigas** [slovensko-digital/priznanie-digital#773]
v utils.ts sa nachadzaju 2 funkcie ktore je nutne odstranit lebo uz sa pouziva matematicke zaukruhlovanie na 2 desatine miesta vsade. 
```ts
export const floorDecimal = (decimal: Decimal) => {
  return decimal.toDecimalPlaces(2, Decimal.ROUND_FLOOR)
}
export const ceilDecimal = (decimal: Decimal) => {
  return decimal.toDecimalPlaces(2, Decimal.ROUND_CEIL)
}
```

mala by sa uz pouzivat iba funkcia `round`

**Comment by Ormi** [comment]
Beriem si to #hackaton23

**Comment by Ormi** [comment]
Riesenie mam pripravene, ale nemozem ani pushnut svoju branch.
