### ISSUE TITLE
Vypnutie odkladu po 31.3.

### ISSUE THREAD

**Issue by MarekVigas** [slovensko-digital/priznanie-digital#777]
Odklad danoveho priznania sa da podat len do 31.3. Od aprila by malo linkovanie na odklad zmiznut z uvodnej stranky.

**Comment by MarekVigas** [comment]
<img width="626" alt="Screenshot 2023-04-12 at 17 51 09" src="https://user-images.githubusercontent.com/11539820/231512963-09f04ca5-6b57-4405-a884-239143767c5e.png">

**Comment by Ormi** [comment]
Beriem si to #hackaton23

**Comment by MatejKozlovsky** [comment]
Pozrám to
