### ISSUE TITLE
Upozornenie ze danovnik sa moze stat platcom preddavkov na dan

### ISSUE THREAD

**Issue by MarekVigas** [slovensko-digital/priznanie-digital#786]
[2022.04.13_011_FO_2022_IM_Preddav_FO.pdf](https://github.com/slovensko-digital/priznanie-digital/files/11272568/2022.04.13_011_FO_2022_IM_Preddav_FO.pdf)

**Comment by Ormi** [comment]
Nove znenie sa nijak nelisi, akurat to uz je na [webe](https://www.financnasprava.sk/sk/elektronicke-sluzby/verejne-sluzby/danove-kalkulacky/vypocet-preddavkov-fo-2023) a nie v pdf, co je super, kedze to mozme pridat ako link do oznamenia a bude vzdy aktualny.

**Comment by Ormi** [comment]
### Zadanie:
Cielom tohto issue je upozronit uzivatela na konci procesu pripravy danoveho priznania, ze prekrocil jeden z dvoch limitov a ze na dalsi rok bude urcite platit preddavky. Oznamit mu, ze financna sprava ho na to tiez upozorni a poskytnut mu link na web FS kde si moze spocitat kolko to bude a ci to bude mesacne alebo kvartalne.

Pripadne mozno dat tento vypocet aj sem, ale to bude skor part 2 :wink:
