### ISSUE TITLE
rozdelit moznost pri podmienkach pre manzelku

### ISSUE THREAD

**Issue by MarekVigas** [slovensko-digital/priznanie-digital#797]
<img width="769" alt="Screenshot 2023-11-13 at 19 09 33" src="https://github.com/slovensko-digital/priznanie-digital/assets/11539820/06a87e17-fe24-49af-8f1b-ae5aba8e7614">

Ten prvy option by som rozdelil na samostatne options 

- Staral/a sa o dieťa do 3 rokov
- Staral/a sa o dieťa do 6 rokov s nepriaznivým zdravotným stavom
- Poberá príspevok na opatrovanie ťažko zdravotne postihnutého

**Comment by LukFil** [comment]
Vzal by som si toto

**Comment by MarekVigas** [comment]
@LukFil mas nejake updates ?

**Comment by LukFil** [comment]
Nemam, prepac, vbehli mi veci. Dnes a zajtra sa pokusim to dokoncit
