### ISSUE TITLE
skontrolovat preddavky na dan

### ISSUE THREAD

**Issue by MarekVigas** [slovensko-digital/priznanie-digital#876]
musime kontrolovat nie dan na uhradu ale zaklad dane alebo niec podobne.
Neviem ci nieco na to zmenil prijem z prenajmu.
<img width="1039" alt="Screenshot 2024-03-06 at 10 10 09" src="https://github.com/slovensko-digital/priznanie-digital/assets/11539820/bc1efcb1-f47b-4d9f-b440-8e8cbb1b9342">

**Comment by Ormi** [comment]
Vypocet je trosku iny tento rok.

https://www.financnasprava.sk/sk/elektronicke-sluzby/verejne-sluzby/danove-kalkulacky/vypocet-preddavkov-fo-2024

Vo vysledky r55 sa pouziva zase.

Akurat vo vypocte mi to mame podla dane a ma to byt podla spominanej r55 **znizeny ciastkovy zaklad dane**.

ToDo:
- [ ] zmen link na odkad na FS za novy
- [ ] uprav vypocet aby vychadzal podla r55
