### ISSUE TITLE
skryt text ked vyprsal odklad

### ISSUE THREAD

**Issue by MarekVigas** [slovensko-digital/priznanie-digital#919]
oznaceny text mozme skryt ak termin na predlzenie vyprsal

<img width="402" alt="Screenshot 2024-06-19 at 17 09 12" src="https://github.com/slovensko-digital/priznanie-digital/assets/11539820/05133106-602e-4802-97de-f7e18c0ceae0">

**Comment by ThePavolC** [comment]
Zdravim, je tato issue stale aktualna ?

**Comment by MarekVigas** [comment]
@ThePavolC je to este aktualne 
feel free to start

**Comment by ThePavolC** [comment]
@MarekVigas https://github.com/slovensko-digital/priznanie-digital/pull/922
